# Configuração do projeto Supabase
project_id = "zbiivgtdamejiwcabmcv"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "auth"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[db.pooler]
enabled = true
port = 54329
pool_mode = "transaction"
default_pool_size = 15
max_client_conn = 100

[realtime]
enabled = true

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://localhost:5173"]
jwt_exp = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[analytics]
enabled = false

# Configuração específica para homologação
[remotes.homologacao]
project_id = "zbiivgtdamejiwcabmcv"
db.pooler.enabled = true
db.pooler.pool_mode = "transaction"
db.pooler.default_pool_size = 10
db.pooler.max_client_conn = 50

[remotes.homologacao.auth]
site_url = "https://gestao-profissional-homologacao.vercel.app"
additional_redirect_urls = ["https://gestao-profissional-homologacao.vercel.app"]

# Configuração específica para produção
[remotes.production]
project_id = "pwksgdjjkryqryqrvyja"
db.pooler.enabled = true
db.pooler.pool_mode = "transaction"
db.pooler.default_pool_size = 20
db.pooler.max_client_conn = 100

[remotes.production.auth]
site_url = "https://gestao-profissional.vercel.app"
additional_redirect_urls = ["https://gestao-profissional.vercel.app"] 