# GitLab CI/CD pipeline com integração Doppler
stages:
  - test
  - build
  - deploy

variables:
  NODE_VERSION: "18"

# Configuração do cache
cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules/

# Instalação do Doppler e dependências
.setup_doppler: &setup_doppler
  - apt-get update && apt-get install -y curl
  - curl -sLf --retry 3 --tlsv1.2 --proto "=https" 'https://packages.doppler.com/public/cli/gpg.DE2A7741A397C129.key' | apt-key add -
  - echo "deb https://packages.doppler.com/public/cli/deb/debian any-version main" | tee /etc/apt/sources.list.d/doppler-cli.list
  - apt-get update && apt-get install -y doppler
  - npm ci

# Testes com Doppler
test:
  stage: test
  image: node:$NODE_VERSION
  script:
    - *setup_doppler
    - doppler run --token=$DOPPLER_TOKEN -- npm run secure:test

# Build com Doppler
build:
  stage: build
  image: node:$NODE_VERSION
  script:
    - *setup_doppler
    - doppler run --token=$DOPPLER_TOKEN -- npm run build:production
  artifacts:
    paths:
      - dist/

# Deploy para GitLab Pages
pages:
  stage: deploy
  image: node:$NODE_VERSION
  script:
    - mkdir -p public
    - cp -r dist/* public/
  artifacts:
    paths:
      - public
  only:
    - main
    - master