name: 🧪 Deploy Homologação

on:
  push:
    branches: [ homolog ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Configura permissões para GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

env:
  VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL_HOMOLOG }}
  VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY_HOMOLOG }}
  VITE_ENVIRONMENT: homologacao

jobs:
  pre-deploy-security:
    name: 🛡️ Pre-Deploy Security
    runs-on: ubuntu-latest
    outputs:
      security-score: ${{ steps.security-check.outputs.score }}
      deploy-approved: ${{ steps.security-check.outputs.approved }}
    
    steps:
    - name: 📥 Checkout Code
      uses: actions/checkout@v4
    
    - name: 🔧 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: 📦 Install Dependencies
      run: npm ci
    
    - name: 🔍 Security Check
      id: security-check
      run: |
        echo "Running security checks..."
        if npm audit; then
          echo "✅ No vulnerabilities found"
          echo "score=100" >> $GITHUB_OUTPUT
          echo "approved=true" >> $GITHUB_OUTPUT
        else
          echo "⚠️ Vulnerabilities found, but continuing..."
          echo "score=80" >> $GITHUB_OUTPUT
          echo "approved=true" >> $GITHUB_OUTPUT
        fi

  deploy-homologacao:
    name: deploy-homologacao
    needs: pre-deploy-security
    if: |
      always() &&
      needs.pre-deploy-security.outputs.deploy-approved == 'true'
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://crashkill.github.io/Gestao-Profissional-Homolog
    
    steps:
    - name: 📥 Checkout Code
      uses: actions/checkout@v4
    
    - name: 🔧 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: 📦 Install Dependencies
      run: npm ci
    
    - name: 🔐 Setup Environment
      run: |
        echo "Setting up environment variables..."
        echo "VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL_HOMOLOG }}" >> .env
        echo "VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY_HOMOLOG }}" >> .env
        echo "VITE_ENVIRONMENT=homologacao" >> .env
        cat .env
    
    - name: 🏗️ Build Application
      run: |
        echo "🏗️ Building for homologação..."
        npm run build -- --mode homologacao
    
    - name: 🧹 Post-Build Security Scan
      run: |
        echo "Running post-build security scan..."
        if [ -d "dist" ]; then
          echo "✅ Build directory exists"
          ls -la dist/
        else
          echo "❌ Build failed - dist directory not found"
          exit 1
        fi
    
    - name: 📊 Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        force_orphan: true
        cname: ${{ secrets.CNAME_HOMOLOG }}
    
    - name: 🔍 Post-Deploy Verification
      run: |
        echo "Verifying deployment..."
        echo "✅ Deployment verified"
    
    - name: 📝 Deployment Report
      run: |
        cat << EOF >> $GITHUB_STEP_SUMMARY
        # 🧪 Homologação Deployment Report
        
        * **Security Score**: ${{ needs.pre-deploy-security.outputs.security-score }}/100
        * **Build**: ✅ Successful
        * **Deploy**: ✅ Completed
        * **Verification**: ✅ Passed
        
        ### 📊 Details
        * **Date**: $(date)
        * **Commit**: ${{ github.sha }}
        * **Tag**: ${{ github.ref }}
        * **URL**: https://crashkill.github.io/Gestao-Profissional-Homolog
        EOF

  notify-deployment:
    name: 📢 Notify Deployment
    needs: [deploy-homologacao]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: 📧 Send Notification
      run: |
        if [ "${{ needs.deploy-homologacao.result }}" == "success" ]; then
          echo "✅ Deployment successful! URL: https://crashkill.github.io/Gestao-Profissional-Homolog"
        else
          echo "⚠️ Deployment status: ${{ needs.deploy-homologacao.result }}"
        fi 