name: Deploy

on:
  push:
    branches:
      - main
      - homolog
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pre-deploy-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run security checks
        run: npm run security-check
        
  deploy-homologacao:
    needs: pre-deploy-security
    if: github.ref == 'refs/heads/homolog'
    runs-on: ubuntu-latest
    environment:
      name: homologacao
      url: https://gestao-profissional-homologacao.vercel.app
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Doppler CLI
        run: (curl -Ls --tlsv1.2 --proto "=https" --retry 3 https://cli.doppler.com/install.sh || wget -t 3 -qO- https://cli.doppler.com/install.sh) | sudo sh
        
      - name: Setup Doppler
        run: doppler setup --token ${{ secrets.DOPPLER_TOKEN }} --project gestao-profissional --config homologacao
        
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest
          
      - name: Link to Supabase project
        run: |
          doppler run -- supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID_HOMOLOG }}
          
      - name: Deploy migrations
        run: |
          doppler run -- supabase db push
          
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          npx vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
          npx vercel build --token=${{ secrets.VERCEL_TOKEN }}
          npx vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
          
  deploy-production:
    needs: pre-deploy-security
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://gestao-profissional.vercel.app
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Doppler CLI
        run: (curl -Ls --tlsv1.2 --proto "=https" --retry 3 https://cli.doppler.com/install.sh || wget -t 3 -qO- https://cli.doppler.com/install.sh) | sudo sh
        
      - name: Setup Doppler
        run: doppler setup --token ${{ secrets.DOPPLER_TOKEN }} --project gestao-profissional --config production
        
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest
          
      - name: Link to Supabase project
        run: |
          doppler run -- supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID_PROD }}
          
      - name: Deploy migrations
        run: |
          doppler run -- supabase db push
          
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          npx vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          npx vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          npx vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} 