name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Update browserslist-db
        run: npx update-browserslist-db@latest

      - name: Build
        run: npm run build

      - name: Check build output
        run: |
          ls -la dist
          echo "Checking if index.html exists..."
          test -f dist/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
          keep_files: true
          clean: true
          commit_message: 'chore: deploy to gh-pages'
          publish_branch: gh-pages
