name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Configura as permissões do job
permissions:
  contents: read
  pages: write
  id-token: write

# Permite que o job atualize o job de deploy
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          # Executa o update:browserslist, mas não falha se houver erros
          npm run update:browserslist || echo "Warning: browserslist update failed, continuing..."

      - name: Build application
        run: |
          echo "Building application..."
          npm run build

      - name: Verify build output
        run: |
          echo "Verifying build output..."
          if [ ! -f dist/index.html ]; then
            echo "❌ Error: index.html not found in dist/"
            ls -la dist/ || true
            exit 1
          fi
          echo "✅ Build verified successfully"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    needs: build-and-deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
